### PR TITLE
Bump `rand` dependencies

### PR DESCRIPTION
**Pull request by LecrisUT**
Trying to package this project as part of a dependency chain in Fedora. It seems this version bump does not change much.

It is not very urgent to include and ship this change since we can make these 2 changes downstream as well, so feel free to decide when you want to bump these dependencies.

### CODE REVIEW

**Comment by mheffner** [comment]
The flapping test is fixed in https://github.com/mheffner/rust-sketches-ddsketch/pull/14 and seems unrelated to this PR.

**Review by mheffner — APPROVED** [review]
Thanks @LecrisUT , this looks fine to me. What package pulls this in?

**Comment by LecrisUT** [comment]
It's in a dependency chain for `atuin` -> `metrics-*` -> `metrics-util`

**Comment by mheffner** [comment]
Cool, good to know. As a Fedora user myself, I'll have to check it out. Cheers!

**Pull request merged**
